#!/usr/bin/env python3
r"""
gen_ecoboost_starters.py — EcoBoost Track-B: seed profitable starter RGOs at 1836 via a
BUILDING HISTORY file (applied at setup, no runtime event => cheap).

For every state of the 40 mod tags that CAN build the RGO (map_data capacity, from
unused_rgo_by_state.csv = "has potential AND builds 0 today") it seeds 1 level of:
  whale (whaling_station)  -> EVERY eligible state            (no cap)
  gold  (gold_mine)        -> EVERY eligible state            (no cap)
  wood  (logging_camp)     -> top 80% of the tag's states BY POP
  iron  (iron_mine)        -> top 40% of the tag's states BY POP
Caps stop a 43-state China from flooding wood/iron, while a small tag (ARG/PAN/SAF) still
gets proportional coverage. Within the cap, the highest-population eligible states win
(JAP: 11 states -> iron cap 4; if only 4 can build iron, all 4 get it; if 5 can, top 4 by pop).

Inputs (hk-config/tools/): unused_rgo_by_state.csv, state_pops.csv, mod-nations.csv.
Outputs:
  mod1/Top40EcoBoostMod/common/history/buildings/zz_eco_starters.txt   (UTF-8 BOM, generated)
  hk-config/tools/flat_history_building_boost.csv                       (tag x building report)

History building form: country-owned, activate_production_methods omitted (game picks a
tech-appropriate default per tag). VERIFY in the first in-game test (error.log).
Usage: python gen_ecoboost_starters.py
"""
import os, csv
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
MOD_HISTORY = os.path.join(HERE, "..", "..", "mod1", "Top40EcoBoostMod",
                           "common", "history", "buildings", "zz_eco_starters.txt")

# RGO token (as it appears in unused_rgo_by_state.rgo) -> short label + state-cap rule.
# cap = None means "every eligible state"; a float means "top <cap*total_states> by pop".
# 2026-06-15: gold + whale DROPPED (user) — they over-seeded into 0-capacity colonial states
# (Bombay gold, Guine/Angola whale -> "can only support 0"). Track-B now seeds only wood + iron.
TARGETS = [
    ("logging_camp",    "wood",  0.80),
    ("iron_mine",       "iron",  0.40),
]
LABELS = [lbl for _, lbl, _ in TARGETS]

# (state, rgo) combos the GAME reported as 0-capacity ("can only support 0") even though
# unused_rgo_by_state.csv lists them buildable (its map_data capacity is unreliable for these
# colonial/hill states). Crude curated exclusion from the 2026-06-15 run; TODO T51 = a proper
# start-capacity re-scan. Bare state tokens match the csv's `state` column.
EXCLUDE = {
    ("HILL_PUNJAB", "logging_camp"), ("HILL_PUNJAB", "iron_mine"),
    ("RAJPUTANA", "logging_camp"),
    ("BALUCHISTAN", "logging_camp"), ("BALUCHISTAN", "iron_mine"),
    ("SISTAN", "logging_camp"), ("SISTAN", "iron_mine"),
    ("IVORY_COAST", "logging_camp"),
    ("GOLD_COAST", "logging_camp"),
    ("GUJARAT", "iron_mine"),
    ("UPPER_ANDALUSIA", "logging_camp"),
    ("MACAO", "logging_camp"),
}


def load_csv(name):
    with open(os.path.join(HERE, name), encoding="utf-8") as f:
        return list(csv.DictReader(f))


def round_half_up(x):
    return int(x + 0.5)


def main():
    tags = {r["tag"]: r["country"] for r in load_csv("mod-nations.csv")}

    # per-state pop + total states per tag
    pop = {}                                   # (tag, state) -> pop
    states_of = defaultdict(set)               # tag -> {states}
    for r in load_csv("state_pops.csv"):
        if r["tag"] in tags:
            pop[(r["tag"], r["state"])] = int(r["pop"])
            states_of[r["tag"]].add(r["state"])

    # eligible (tag, state) per RGO token  (unused = can-afford AND has-none)
    eligible = defaultdict(lambda: defaultdict(list))   # rgo -> tag -> [state]
    for r in load_csv("unused_rgo_by_state.csv"):
        if r["tag"] in tags and (r["state"], r["rgo"]) not in EXCLUDE:
            eligible[r["rgo"]][r["tag"]].append(r["state"])

    # decide which states get which building
    seed = defaultdict(lambda: defaultdict(list))       # tag -> state -> [building_token]
    report = {t: {lbl: 0 for lbl in LABELS} for t in tags}
    for rgo, lbl, cap_pct in TARGETS:
        for tag in tags:
            cand = eligible[rgo].get(tag, [])
            if not cand:
                continue
            cand = sorted(cand, key=lambda s: pop.get((tag, s), 0), reverse=True)
            if cap_pct is not None:
                cap = round_half_up(cap_pct * len(states_of[tag]))
                cand = cand[:cap]
            for s in cand:
                seed[tag][s].append("building_" + rgo)
                report[tag][lbl] += 1

    # ---- write the history file (UTF-8 BOM, tabs) ----
    os.makedirs(os.path.dirname(MOD_HISTORY), exist_ok=True)
    lines = [
        "# =============================================================================",
        "# Top40EcoBoostMod - eco starter RGOs  (GENERATED by hk-config/tools/gen_ecoboost_starters.py)",
        "# DO NOT HAND-EDIT - re-run the generator to change.",
        "# Seeds 1 level of profitable RGOs at 1836 to states of the 40 mod tags that CAN",
        "# build them (map_data capacity) and have NONE yet:",
        "#   whale + gold -> every eligible state.   wood -> top 80% of a tag's states by pop.",
        "#   iron -> top 40% of a tag's states by pop.   (caps: no China flood / small tags covered)",
        "# Country-owned, default PM (activate_production_methods omitted) - verify in error.log.",
        "# =============================================================================",
        "BUILDINGS = {",
    ]
    n_states = n_builds = 0
    for tag in sorted(seed):
        for state in sorted(seed[tag]):
            n_states += 1
            # unused_rgo_by_state.csv stores BARE state names (BUENOS_AIRES); the history scope
            # needs the STATE_ token (s:STATE_BUENOS_AIRES) or every ref errors "Failed to scope
            # to state region by key" (was 1179 errors). Normalise here.
            st = state if state.startswith("STATE_") else f"STATE_{state}"
            lines.append(f"\ts:{st} = {{")
            lines.append(f"\t\tregion_state:{tag} = {{")
            for bt in seed[tag][state]:
                n_builds += 1
                lines.append("\t\t\tcreate_building = {")
                lines.append(f'\t\t\t\tbuilding = "{bt}"')
                lines.append("\t\t\t\tadd_ownership = {")
                lines.append("\t\t\t\t\tcountry = {")
                lines.append(f'\t\t\t\t\t\tcountry = "c:{tag}"')
                lines.append("\t\t\t\t\t\tlevels = 1")
                lines.append("\t\t\t\t\t}")
                lines.append("\t\t\t\t}")
                lines.append("\t\t\t\treserves = 1")
                lines.append("\t\t\t}")
            lines.append("\t\t}")
            lines.append("\t}")
    lines.append("}")
    with open(MOD_HISTORY, "w", encoding="utf-8-sig", newline="\r\n") as f:
        f.write("\n".join(lines) + "\n")

    # ---- write the report ----
    out_csv = os.path.join(HERE, "flat_history_building_boost.csv")
    with open(out_csv, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["tag", "country", "total_states"] + LABELS + ["total_buildings"])
        for tag in sorted(tags, key=lambda t: -sum(report[t].values())):
            row = report[tag]
            tot = sum(row.values())
            w.writerow([tag, tags[tag], len(states_of[tag])] + [row[l] for l in LABELS] + [tot])

    print(f"wrote zz_eco_starters.txt: {n_builds} buildings across {n_states} state-blocks")
    print(f"wrote flat_history_building_boost.csv")
    grand = {l: sum(report[t][l] for t in tags) for l in LABELS}
    print("  totals: " + " ".join(f"{l}={grand[l]}" for l in LABELS) + f"  (all={sum(grand.values())})")
    for t in ("CHI", "JAP", "BRZ", "ARG", "PAN", "SOK"):
        r = report[t]
        print(f"  {t}: " + " ".join(f"{l}={r[l]}" for l in LABELS) + f"  (states={len(states_of[t])})")


if __name__ == "__main__":
    main()
