#!/usr/bin/env python3
"""gen_pvtcap_state_caps.py — PvtCapCtrlMod: emit the static per-state-region industry
level cap as a history file that sets var:zw_mfg_cap once at game start (fixed, no pulse).

Cap rule (from total START pop, all owners summed, see data_state_region_pop.csv):
    cap = max(MIN_CAP, total_pop // DIVISOR)            # strict floor, no boundary inversion
    MIN_CAP = 40   (smallest state still gets 40 industry slots, headroom for migration/births)
    DIVISOR = 24000  (~33% workforce / ~8000 effective manufacturing share per level after other
                      sectors take their cut; tune here, the in-mod decade multiplier adds growth)

Source : data_state_region_pop.csv  (owning script: anal_state_region_pop.py)
Output : mod1-inov/PvtCapCtrlMod/common/history/states/zw_cpc_state_caps.txt  (UTF-8 BOM)
Usage  : python gen_pvtcap_state_caps.py
"""
import os, csv

HERE = os.path.dirname(os.path.abspath(__file__))
CONTAINER = os.path.abspath(os.path.join(HERE, "..", ".."))          # victoria-3-mod\
SRC = os.path.join(HERE, "data_state_region_pop.csv")
OUT = os.path.join(CONTAINER, "mod1-inov", "PvtCapCtrlMod",
                   "common", "history", "states", "zw_cpc_state_caps.txt")

MIN_CAP = 40
DIVISOR = 24_000


def cap_for(pop):
    return max(MIN_CAP, pop // DIVISOR)


def main():
    with open(SRC, encoding="utf-8-sig") as f:
        rows = [(r["state_region"], int(r["total_pop"])) for r in csv.DictReader(f)]
    rows.sort(key=lambda x: x[0])  # by state name -> stable diffs

    lines = [
        "# GENERATED by hk-config/tools/gen_pvtcap_state_caps.py from data_state_region_pop.csv (Vic3 1.13.8).",
        "# DO NOT HAND-EDIT. Sets each state-region's FIXED industry level cap (var:zw_mfg_cap), once at game start.",
        f"# Rule: cap = max({MIN_CAP}, total_start_pop // {DIVISOR:,}). Trailing comment = total start pop (all owners).",
        "STATES = {",
    ]
    for state, pop in rows:
        lines.append(
            f"\ts:{state} = {{ set_variable = {{ name = zw_mfg_cap value = {cap_for(pop)} }} }}  # pop {pop:,}"
        )
    lines.append("}")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write("\n".join(lines))

    floored = sum(1 for _, p in rows if cap_for(p) == MIN_CAP)
    print(f"wrote {OUT}")
    print(f"  {len(rows)} state-regions  | at MIN({MIN_CAP}): {floored}  | scaled: {len(rows) - floored}")

    # ---- PART 2: sanity checks + unit tests (fail loudly) ----
    caps = {s: cap_for(p) for s, p in rows}
    pops = dict(rows)
    below = {s: c for s, c in caps.items() if c < MIN_CAP}
    assert not below, f"SANITY FAIL: {len(below)} cap(s) below MIN {MIN_CAP}: {list(below.items())[:5]}"
    print(f"  [PASS] sanity: all {len(caps)} caps >= {MIN_CAP}")

    assert "STATE_MIDLANDS" in caps, "UNIT FAIL: STATE_MIDLANDS missing from data"
    mid = caps["STATE_MIDLANDS"]
    assert mid == max(MIN_CAP, pops["STATE_MIDLANDS"] // DIVISOR)
    print(f"  [PASS] unit MIDLANDS: pop={pops['STATE_MIDLANDS']:,} -> cap={mid}")
    assert 100 <= mid <= 120, f"UNIT FAIL: MIDLANDS cap {mid} outside expected ~107 band"
    print(f"  [PASS] unit MIDLANDS cap {mid} within expected band (100..120)")


if __name__ == "__main__":
    main()
